# Generated by Django 6.0.3 on 2026-04-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0003_demandeinscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='hospital',
            name='password',
            field=models.CharField(blank=True, default='admin123', max_length=200),
        ),
    ]
