# Generated by Django 6.0.3 on 2026-05-06 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0004_hospital_email_hospital_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='horaires',
            field=models.CharField(blank=True, default='8h - 17h', max_length=100),
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('specialite', models.CharField(max_length=200)),
                ('telephone', models.CharField(blank=True, default='', max_length=20)),
                ('disponible', models.BooleanField(default=True)),
                ('heure_debut', models.TimeField(default='08:00')),
                ('heure_fin', models.TimeField(default='17:00')),
                ('jours_travail', models.CharField(default='Lun-Ven', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medecins', to='hospitals.hospital')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medecins', to='hospitals.service')),
            ],
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_patient', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=20)),
                ('motif', models.TextField(blank=True, default='')),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('annule', 'Annulé'), ('termine', 'Terminé')], default='en_attente', max_length=20)),
                ('numero_rdv', models.CharField(blank=True, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendezvous', to='hospitals.hospital')),
                ('medecin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rendezvous', to='hospitals.medecin')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rendezvous', to='hospitals.service')),
            ],
        ),
    ]
