# Generated by Django 6.0.3 on 2026-05-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0005_service_horaires_medecin_rendezvous'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeinscription',
            name='motdepasse',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
