# Generated by Django 6.0.3 on 2026-06-07 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0006_demandeinscription_motdepasse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='demandeinscription',
            options={'ordering': ['-created_at'], 'verbose_name': "Demande d'inscription", 'verbose_name_plural': "Demandes d'inscription"},
        ),
        migrations.AlterModelOptions(
            name='hospital',
            options={'verbose_name': 'Hôpital', 'verbose_name_plural': 'Hôpitaux'},
        ),
        migrations.AlterModelOptions(
            name='medecin',
            options={'verbose_name': 'Médecin', 'verbose_name_plural': 'Médecins'},
        ),
        migrations.AlterModelOptions(
            name='rendezvous',
            options={'ordering': ['-created_at'], 'verbose_name': 'Rendez-vous', 'verbose_name_plural': 'Rendez-vous'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AddField(
            model_name='demandeinscription',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demandeinscription',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demandeinscription',
            name='adresse',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='demandeinscription',
            name='responsable',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='demandeinscription',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medecins', to='hospitals.service'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='heure',
            field=models.TimeField(default='08:00'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='medecin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendezvous', to='hospitals.medecin'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='nom_patient',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendezvous', to='hospitals.service'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rendezvous', to='hospitals.patient'),
        ),
    ]
